### ISSUE TITLE
关于模型训练方面的问题

### ISSUE THREAD

**Issue by hervey-github** [yosaa/dnfm-auto#27]
请教您关于模型训练方面的几个问题：
1、您内置的标签hero只有一个分类，所有不同职业都标注成hero是否会影响识别精度？
2、同理怪物可能体型、外形差异比较大，同样只有一个分类标签，会不会影响训练结果，倒地怪物似乎不会起到作用是否依然需要标注？
3、如果新增了角色想要适配是否需要全部重新训练，还是说按照不同的类型训练多个模型？怎样跟利于后续升级

**Comment by yosaa** [comment]
1，2 两点只要数据集做的好一点，完全不是需要担心的问题。3. last.pt 文件就是用于加入新数据后再训练的

**Comment by hervey-github** [comment]
感谢您的解答
